title: "Raphael Geddert"
name: "Raphael Geddert"
logo: '/assets/img/me.jpg'
favicon: '/assets/img/me.jpg'
description: 'Hello!'
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include: ["_pages"]
permalink: /:title/
is_project_page: false
is_user_page: false
