title: "Raphael Geddert"
name: "Raphael Geddert"
logo: '/assets/img/me.jpg'
favicon: '/assets/img/me.jpg'
description: 'A day in the life'
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include: ["_pages"]
permalink: /:title/
